stty -ixon

export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"

if [[ -f /usr/bin/iceweasel ]]; then
	export BROWSER="iceweasel"
else
	export BROWSER="firefox"
fi

shopt -s autocd

#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
	#exec startx
#fi


#Basic Aliases
alias v="vim"
#alias sv="sudo vim"
alias r="ranger"
alias ls='ls -hN --color=auto --group-directories-first'
alias lsa='ls -A'
g() { cd $1 && ls -a ;}

alias mutt="mutt -F ~/.config/scripts/mutt/muttrc"
alias mocp="mocp --config ~/.config/scripts/moc/config"
alias calcurse="calcurse -D ~/.config/scripts/calcurse"
alias weechat="weechat -d ~/.config/scripts/weechat"
alias tmux="tmux -f ~/.config/i3/scripts/tmux.conf"

#Term only
alias mute="pamixer -m"
alias vd="pamixer -d 10"
alias vu="pamixer -i 10"
alias p="mocp -G &> /dev/null"
alias next="mocp -f &> /dev/null"
alias prev="mocp -r &> /dev/null"
alias mnt="sudo bash ~/.config/i3/scripts/mount.sh"
alias umnt="sudo bash ~/.config/i3/scripts/unmount.sh"
alias sdn="sudo shutdown now"

alias screenfetch="screenfetch -t"
alias yt="youtube-dl -ic"
alias yta="youtube-dl -xic"

alias newnet="sudo systemctl restart NetworkManager"
alias atltime="sudo timedatectl set-timezone America/New_York && i3 restart"
alias tuctime="sudo timedatectl set-timezone America/Phoenix && i3 restart"

alias youtube="youtube-viewer"
alias YT="youtube-viewer"
alias syt="youtube-viewer"

alias TC='find . -maxdepth 1 -regextype gnu-awk -regex "^.*\.(pyc|pyo|bak|swp|aux|log|nav|out|snm|toc|bcf|run\.xml|synctex\.gz|blg|bbl)" -delete'

alias ethspeed="speedometer -r enp0s25"

note() { echo "$@" >> ~/notes ;}

alias extract="~/.config/i3/script/ext.sh"

backup() { cp $1 $1.bu ;}

#alias man="w3mman"

alias mailsync="bash ~/.config/i3/scripts/mailsyncloop.sh"

alias wifispeed="speedometer -r wlp2s0"

alias bbs="python ~/.config/i3/bumblebee-status/bumblebee-status"




